---
title: 错误和异常处理
toc: true
date: 2019-11-17
---

# 7 Errors and Exception Handling（错误和异常处理）

在数据分析应用中，许多函数只能用于特定的输入。比如 float 能把 string 变为浮点数，但如果有不正确的输入的话会报错：


```py
float('1.2345')
float('something')
```

输出：
```
1.2345
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<iPython-input-47-439904410854> in <module>()
----> 1 float('something')

ValueError: could not convert string to float: 'something'
```

假设我们想要这个 float 失败的优雅一些，返回输入的参数。我们可以用 try/except：

这个 except 的部分只有当 float(x) 引发异常的时候才会执行：

```py
def attempt_float(x):
    try:
        return float(x)
    except:
        return x
attempt_float('1.2345')
attempt_float('something')
```

输出：
```
1.2345
'something'
```

当然，float也可能引发除了 ValueError 之外的异常：


```
float((1, 2))
```
输出：

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<iPython-input-53-842079ebb635> in <module>()
----> 1 float((1, 2))

TypeError: float() argument must be a string or a number, not 'tuple'
```

你可能只想控制 ValueError，因为如果是 TypeError 的话，错误提示对你 debug 是有帮助的：


```py
def attempt_float(x):
    try:
        return float(x)
    except ValueError:
        return x
attempt_float((1, 2))
```
输出：

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<iPython-input-55-9bdfd730cead> in <module>()
----> 1 attempt_float((1, 2))

<iPython-input-54-84efde0a7059> in attempt_float(x)
      1 def attempt_float(x):
      2     try:
----> 3         return float(x)
      4     except ValueError:
      5         return x

TypeError: float() argument must be a string or a number, not 'tuple'
```

当然，你也可以捕捉多个不同的异常：

```py
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x
```

在某些情况下，你不想抑制任何异常，但你想希望执行某些代码，不论 try 里的代码成功执行与否。这样的话，需要用的 finally :


```py
f = open(path, 'w')
try:
    write_to_file(y)
finally:
    f.close()
```

这样的处理会始终会让 f 关闭。同样的，你可以在 try 里的代码成功执行后，让某些代码执行：


```py
f = open(path, 'w')
try:
    write_to_file(f)
except:
    print('Failed')
else:
    print('Succeeded')
finally:
    f.close()
```
